site_name: The Couple Notebook
site_description: A notebook for couples to share their thoughts and memories
site_author: Carla

repo_name: ccarlaa/the-couple-notebook
repo_url: https://github.com/ccarlaa/the-couple-notebook
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: custom-icons/icon_night
        name: Modo Claro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: custom-icons/icon_light
        name: Modo Escuro

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
  
plugins: 
  - search:
      lang: pt-BR

markdown_extensions:
  - attr_list
  - markdown.extensions.md_in_html
  - md_in_html
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - mdx_math
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - Home: index.md
  - Matemática: 
    - Conceitos Gerais:
      - Conjuntos: matematica/conceitos-gerais/conjuntos.md
      - Composição Interna: matematica/conceitos-gerais/composicao-interna.md
      - Grupo: matematica/conceitos-gerais/grupo.md
      - Corpo: matematica/conceitos-gerais/corpo.md
      - Anel:  matematica/conceitos-gerais/anel.md
      - Polinômios: matematica/conceitos-gerais/polinomios.md
      - Função Polinomial: matematica/conceitos-gerais/funcao_polinomial.md
      - Espaços: matematica/conceitos-gerais/espacos.md
      - Produto Cartesiano: matematica/conceitos-gerais/produto-cartesiano.md
      - Produto Interno: matematica/conceitos-gerais/produto-interno.md 
      - Sequência de Cauchy: matematica/conceitos-gerais/cauchy-sequence.md
    - Álgebra Linear: 
      - Teorema Fundamental da Álgebra: matematica/ial/tfa.md
      - Norma: matematica/ial/norma.md
      - Espaço Hilbertiano: matematica/ial/espaco-hilbertiano.md
  - About: about.md